from app.models.hotel import Hotel
from app.models.user import User
from app.models.room import Room
from app.models.client import Client
from app.models.reservation import Reservation
from app.models.stay import Stay
from app.models.inventory_product import InventoryProduct
from app.models.inventory_movement import InventoryMovement
from app.models.client_consumption import ClientConsumption